spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/chusui_db
    username: chusui_db_driver
    password: testpassword
    driverClassName: org.postgresql.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  port: 7777